[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["jayvalentine <jayv136@gmail.com>"]
edition = "2018"

[lib]
name = "aoc"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
